version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - main: main.go
    binary: qbit
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_arm64
    flags:
      - -trimpath
    ldflags:
      - s -w -X main.Version={{.Version}}

release:
  prerelease: auto

checksum:
  name_template: "sha256sums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'