server:
  host: ""
  username: ""
  password: ""
torrent:
  default-save-path: ""
  default-save-category: ""
  default-save-tags: ""
jackett:
  host: ""
  api-key: ""
  cookie: "Jackett:xx"
emby:
  host: ""
  api-key: ""
  user: ""